package com.mydemo.demoproject.Entity.enumlist;

public enum CancelReason {

    INCORRECT_SIZE_ORDER,
    PRODUCT_NOT_REQUIRED_ANYMORE,
    CASH_ISSUE,
    ORDER_BY_MISTAKE,
    WANT_TO_CHANGE_STYLE_OR_COLOUR,
    DELAYED_DELIVERY_CANCELLATION,
    DUPLICATED_ORDER,
}
